/**
 * webSocket Methods
 */

export const METHOD_CREATE_ROOM = 'METHOD_CREATE_ROOM';
export const METHOD_JOIN_ROOM = 'METHOD_JOIN_ROOM';
export const METHOD_LEAVE_ROOM = 'METHOD_LEAVE_ROOM';

export const METHOD_SEND_ROOM_CHAT_MESSAGE = 'METHOD_SEND_ROOM_CHAT_MESSAGE';
export const METHOD_SEND_SESSION_DESC_OFFER = 'METHOD_SEND_SESSION_DESC_OFFER';
export const METHOD_SEND_SESSION_DESC_ANSWER = 'METHOD_SEND_SESSION_DESC_ANSWER';
export const METHOD_SEND_ICE_CANDIDATE = 'METHOD_SEND_ICE_CANDIDATE';

export const METHOD_MY_ACCOUNT_INFO = 'METHOD_MY_ACCOUNT_INFO';
export const METHOD_CHANGE_NICKNAME = 'METHOD_CHANGE_NICKNAME';
