/**
 * webSocket Methods
 */

export const METHOD_CREATE_ROOM = 'METHOD_CREATE_ROOM';
export const METHOD_JOIN_ROOM = 'METHOD_JOIN_ROOM';
export const METHOD_LEAVE_ROOM = 'METHOD_LEAVE_ROOM';
export const MEMBER_LEAVE_ROOM = 'MEMBER_LEAVE_ROOM';
export const METHOD_JOIN_ROOM_SEND_PEER_CONNECTION_OFFER = 'METHOD_JOIN_ROOM_SEND_PEER_CONNECTION_OFFER';
export const METHOD_JOIN_ROOM_RECEIVE_PEER_CONNECTION_OFFER = 'METHOD_JOIN_ROOM_RECEIVE_PEER_CONNECTION_OFFER';
export const METHOD_JOIN_ROOM_SEND_PEER_CONNECTION_ANSWER = 'METHOD_JOIN_ROOM_SEND_PEER_CONNECTION_ANSWER';
export const METHOD_JOIN_ROOM_RECEIVE_PEER_CONNECTION_ANSWER = 'METHOD_JOIN_ROOM_RECEIVE_PEER_CONNECTION_ANSWER';
export const METHOD_SEND_ICE = 'METHOD_SEND_ICE';
export const METHOD_RECEIVE_ICE = 'METHOD_RECEIVE_ICE';
